### PR TITLE
Compiling on stable. Also fixed panic when region ID is not found

### PR DESCRIPTION
**Pull request by Snnappie**
Compiles on stable 1.39.0. Tests still require nightly because of the use of specialization.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@Snnappie I used some of this in #124 which gets `cargo test` working too.

**Comment by Hoverbear** [comment]
@Snnappie Could you resolve the conflicts? Then we should be good to merge!

**Comment by Snnappie** [comment]
@Hoverbear Done

**Comment by nrc** [comment]
@Snnappie thanks for updating the branch. There is a compilation error, could you fix it please?
